<?php
$rounds = $this->report->getRounds();
?>

<? /* attackers */ ?>
<? foreach ($rounds[0]->getAttackers() as $fleet): ?>
    [color=red][b]<?= $this->translate("Attacker") ?>[/b][/color] [b][size=12][color=#ff00ff]<?= $fleet->getPlayer() . "[/color][/size][/b]\n" ?>
    (6) [color=#ff99ff]________________________________________________[/color] (6)

    <? foreach ($fleet->getShips() as $ship): ?>
        <?= $this->formatShip(true, $ship); ?>
    <? endforeach; ?>
    (6)[color=#ff99ff]_________________________________________ [/color](6)

<? endforeach; ?>

<? /* defenders */ ?>
<? foreach ($rounds[0]->getDefenders() as $fleet): ?>
    [color=green][b]<?= $this->translate("Defender") ?>[/b][/color] [size=12][b][color=#00ff00]<?= $fleet->getPlayer() . "[/color][/size][/b]\n" ?>
    [color=green]________________________________________________[/color]

    <? foreach ($fleet->getShips() as $ship): ?>
        <?= $this->formatShip(false, $ship); ?>
    <? endforeach; ?>
    [color=green]_________________________________________[/color]

<? endforeach; ?>
