<?php
$rounds = $this->report->getRounds();

$lastRound = $rounds[count($rounds) - 1];
$firstRound = $rounds[0];

$firstFleets = $firstRound->getAttackers();
?>


<? /* attackers */ ?>
<? foreach ($lastRound->getAttackers() as $key => $fleet): ?>
    [color=red][b]<?= $this->translate("Attacker") ?>[/b][/color] [size=12][b][color=#ff00ff]<?= $fleet->getPlayer() . "[/color][/b][/size]\n" ?>
    (6) [color=#ff99ff]________________________________________________[/color] (6)

    <? if (count($fleet->getShips()) < 1): ?>
    [b][size=12][color=#ff0000]<?= $this->translate("Destroyed!") ?>[/color][/size][/b]
    <? else: ?>
        <? if (isset($firstFleets[$key])): ?>
            <? $oldFleet = $firstFleets[$key]; ?>
            <? /* we have old data about the fleet */ ?>
            <? foreach ($oldFleet->getShips() as $ship): ?>
                <?= $this->formatShip(true, $ship, $fleet); ?>
            <? endforeach; ?>
        <? else: ?>
            <? foreach ($fleet->getShips() as $ship): ?>
                <?= $this->formatShip(true, $ship); ?>
            <? endforeach; ?>
        <? endif; ?>
    <? endif; ?>
    (6) [color=#ff99ff]_________________________________________[/color] (6)

<? endforeach; ?>

<? /* defenders */
$firstFleets = $firstRound->getDefenders(); ?>
<? foreach ($lastRound->getDefenders() as $key => $fleet): ?>
    [color=green][b]<?= $this->translate("Defender") ?>[/b][/color] [size=12][b][color=#00ff00]<?= $fleet->getPlayer() . "[/color][/b][/size]\n" ?>
    [color=green]________________________________________________[/color]

    <? if (count($fleet->getShips()) < 1): ?>
    [b][size=12][color=#ff0000]<?= $this->translate("Destroyed!") ?>[/color][/size][/b]
    <? else: ?>
        <? if (isset($firstFleets[$key])): ?>
            <? $oldFleet = $firstFleets[$key]; ?>
            <? /* we have old data about the fleet */ ?>
            <? foreach ($oldFleet->getShips() as $ship): ?>
                <?= $this->formatShip(false, $ship, $fleet); ?>
            <? endforeach; ?>
        <? else: ?>
            <? foreach ($fleet->getShips() as $ship): ?>
                <?= $this->formatShip(false, $ship); ?>
            <? endforeach; ?>
        <? endif; ?>
    <? endif; ?>
    [color=green]_________________________________________[/color]

<? endforeach; ?>

