<?php
function formatNumber($number, $color = false)
{
	$number = number_format($number, 0, ',', '.');
	
	if ($color) {
		return '[color=#3183E7][b]' . $number . '[/b][/color]';
	} else {
		return $number;
	}
}
?>
[quote][center]De volgende vloten kwamen elkaar tegen op <?php
echo $this->time['date'];
if ($this->options['showTime']) {
    echo ' ' . $this->time['time'];
} else {
    echo ' --:--:--';
}
?> , toen het tot een gevecht kwam:

<? /* the first round, attackers */ ?>
<? foreach ($this->rounds[0]['attackers'] as $slot): ?>
    [color=red][b]Aanvaller[/b][/color] <?= $slot['player']['name'] ?> ([X:XXX:XX])
    Wapens: XXX% Schilden: XXX% Romp beplating: XXX%
    [color=red]________________________________________________[/color]
    <? foreach ($slot['fleet'] as $ship => $number): ?>
        [color=#FC850C]<?= $ship ?> <?= formatNumber($number) ?>[/color]
    <? endforeach; ?>
    [color=red]_________________________________________[/color]

<? endforeach; ?>

<? /* the first round */ ?>
<? foreach ($this->rounds[0]['defenders'] as $slot): ?>
    [color=green][b]Verdediger[/b][/color] <?= $slot['player']['name'] ?> ([X:XXX:XX])
    Wapens: XXX% Schilden: XXX% Romp beplating: XXX%
    [color=green]________________________________________________[/color]
    <? foreach ($slot['fleet'] as $ship => $number): ?>
        [color=#1C84BE]<?= $ship ?> <?= formatNumber($number) ?>[/color]
    <? endforeach; ?>
    [color=green]_________________________________________[/color]

<? endforeach; ?>

<?= $this->options['middleText'] ?>


<?php
// make some simple calculations

$last = count($this->rounds) - 1;

/* the first round, attackers */ ?>
<? foreach ($this->rounds[$last]['attackers'] as $slot): ?>
    [color=red][b]Aanvaller[/b][/color] <?= $slot['player']['name'] ?> ([X:XXX:XX])
    [color=red]________________________________________________[/color]
    <? if (empty($slot['fleet'])): ?>
    	[b]Vernietigd![/b]
    <? else: ?>
        <? foreach ($slot['fleet'] as $ship => $number): ?>
            [color=#FC850C]<?= $ship ?> <?= formatNumber($number) ?>[/color]
        <? endforeach; ?>
    <? endif; ?>
    [color=red]_________________________________________[/color]

<? endforeach; ?>

<? /* the first round */ ?>
<? foreach ($this->rounds[$last]['defenders'] as $slot): ?>
    [color=green][b]Verdediger[/b][/color] <?= $slot['player']['name'] ?> ([X:XXX:XX])
    [color=green]________________________________________________[/color]
    <? if (empty($slot['fleet'])): ?>
    	[b]Vernietigd![/b]
    <? else: ?>
        <? foreach ($slot['fleet'] as $ship => $number): ?>
            [color=#1C84AE]<?= $ship ?> <?= formatNumber($number) ?>[/color]
        <? endforeach; ?>
    <? endif; ?>
    [color=green]_________________________________________[/color]

<? endforeach; ?>

<? /* Make up the results */ ?>

<? if ($this->result['winner'] == Kokx_Parser_CrashReport::NONE): ?>
	Het gevecht eindigt in een remise.
<? elseif ($this->result['winner'] == Kokx_Parser_CrashReport::ATTACKER): ?>
	De aanvaller heeft het gevecht gewonnen!
<? else: ?>
	De verdediger heeft het gevecht gewonnen!
<? endif; ?>
De aanvaller steelt:
<? if ($this->result['winner'] == Kokx_Parser_CrashReport::ATTACKER): ?>
	<?= formatNumber($this->result['stolen']['metal'], true) ?> Metaal, <?= formatNumber($this->result['stolen']['crystal'], true) ?> Kristal, <?= formatNumber($this->result['stolen']['deut'], true) ?> Deuterium
<? else: ?>
	- Metaal, - Kristal en - Deuterium
<? endif; ?>

De aanvaller heeft een totaal van <?= formatNumber($this->result['attackerlosses'], true) ?> Eenheden verloren.
De verdediger heeft een totaal van <?= formatNumber($this->result['defenderlosses'], true) ?> Eenheden verloren.
Op deze coördinaten in de ruimte zweven nu <?= formatNumber($this->result['debris']['metal'], true) ?> Metaal en <?= formatNumber($this->result['debris']['crystal'], true) ?> Kristal.
<? if ($this->result['moonchance'] > 0): ?>
	De kans dat een maan ontstaat uit het puin is <?= formatNumber($this->result['moonchance'], true) ?> %
<? endif; ?>
<? /* and a link to the A Team site*/ ?>
[size=10][url=http://converter.ateam-ogame.nl/]Converted by the A Team CR converter 1.0.0[/url][/size][/center][/quote]