<?php
/**
 * This file is part of Kokx's CR Converter.
 *
 * Kokx's CR Converter is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Kokx's CR Converter is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Kokx's CR Converter.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category   KokxConverter
 * @license    http://www.gnu.org/licenses/gpl.txt
 * @copyright  Copyright (c) 2009 Kokx
 * @package    Kokx_Render
 */
?>
<html>

<head>
<title>Kokx's OGame CR converter</title>

<script type="text/javascript">
function toggleOptions()
{
	var options = document.getElementById('options');
	var link    = document.getElementById('hide');

	if (options.style.display == 'none') {
		options.style.display = 'block';
		link.innerHTML = 'Verberg Opties';
	} else {
		options.style.display = 'none';
		link.innerHTML = 'Toon Opties';
	}
}
</script>
<style type="text/css">
body {
	background-color: #0A101D;
	margin: 0px;
	padding: 0px;
	color: #7B90B8;
	font-family: Tahoma,Helvetica;
	font-size: 13px;
}
a:link, a:visited, a:active {
	color: #B0C4DE;
}
a:hover {
	color: #FFFFFF;
}

div#header {
	/*margin-left: auto;
	margin-right: auto;
	width: 520px;*/
	text-align: center;
}
div#adsense {
	margin-left: auto;
	margin-right: auto;
	width: 728px;
}

div#container {
	background-color: #171E2F;
	margin-left: auto;
	margin-right: auto;
	width: 933px;
	border: 1px solid #000000;
}

input, select {
	border: 1px solid #000000;
	background-color: #2F374C;
	color: #7B90B8;
	width: 181px;
}
input#submit {
	width: auto;
}

input#title {
	border: 1px solid #000000;
	background-color: #1F273C;
	color: #7B90B8;
}

textarea {
	border: 1px solid #000000;
	background-color: #1F273C;
	color: #7B90B8;
}

div#cr-container {
	vertical-align: top;
	padding: 15px;
}

div#cr-left {
	vertical-align: top;
	float: left;
	margin-top: -1px;
}
div#cr-right {
	vertical-align: top;
	float: right;
}
div#cr-clear {
	clear: both;
}

div#options-container {
	border: 1px solid #000000;
	margin: 15px;
	margin-top: -15px;
}
div#options {
	border-top: 1px solid #000000;
	padding: 5px;
}
div#options table {
	width: 100%;
	/*border: 1px solid #000000;*/
	border-collapse: collapse;
}
div#options td {
	font-size: 10pt;
	width: 25%;
	/*border: 1px solid #000000;*/
}
div#options-top {
	padding: 5px;
}

div#submit-container {
	margin-left: 15px;
	margin-top: -20px;
	margin-bottom: 28px;
}
pre.xdebug-var-dump {
    background-color: #FFFFFF;
    color: #000000;
}
</style>
</head>

<body>
<div id="container">
	<br />
	<div id="header">
		<h1>Kokx's OGame CR converter</h1>
	</div>
	<br />
	<div id="adsense">
		<script type="text/javascript"><!--
        google_ad_client = "<?= GOOGLE_AD_CLIENT ?>";
        google_ad_slot = "<?= GOOGLE_AD_SLOT ?>";
        google_ad_width = 728;
        google_ad_height = 90;
        //-->
        </script>
        <script type="text/javascript"
        src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
        </script>
	</div>
    <form method="post" action="">
    <div id="cr-container">
        <? if ($this->error): ?>
        	Incorrect gevechtsrapport
        <? endif; ?>
        <div id="cr-left">
            <?= $this->formTextarea('report', $this->report, array('rows' => 22, 'cols' => 60)) ?>
        </div>
        <div id="cr-right">
        	Titel: <?= $this->formText('title', $this->title, array('style' => 'width: 406px;')) ?><br />
            <?= $this->formTextarea('output', empty($this->rounds) ? '': $this->render('report/' . $this->theme . '.phtml'), array('cols' => 60, 'style' => 'height: 325px;')) ?>
        </div>
        <div id="cr-clear">&nbsp;</div>
    </div>
    <div id="submit-container">
        <?= $this->formSubmit('submit', 'Converteer!') ?>
    </div>
    <div id="options-container">
    	<div id="options-top">
    		<a href="javascript: void(0)" id="hide" onclick="toggleOptions()">Verberg Opties</a>
    	</div>
        <div id="options">
        	<h2>Algemene opties</h2>
        	<table border="0">
        		<tr>
        			<td><label for="theme">Skin</label></td>
        			<td><?= $this->formSelect('theme', $this->theme, null, array(
           				'kokx'         => 'kokx',
           				'kokx-nolines' => 'kokx-nolines',
           				'tsjerk'       => 'Albert Fish',
        			    'virus'        => 'ViRuS'
        			)) ?></td>
        			<td><label for="hidetime">Verberg de tijd</label></td>
        			<td><?= $this->formCheckbox('hidetime', null, array('checked' => $this->options['hideTime'])) ?></td>
        		</tr>
        		<tr>
        			<td><label for="middletext">Tekst in het midden van de CR</label></td>
        			<td><?= $this->formText('middletext', $this->options['middleText']) ?></td>
        			<td><label for="merge_fleets">Voeg vloten samen</label></td>
        			<td><?= $this->formCheckbox('merge_fleets', null, array('checked' => $this->options['mergeFleets'])) ?></td>
        		</tr>
        	</table>
            <div>
            	<br />
            	<hr />
            	<h2>Naraids</h2>
            	<?= $this->formTextarea('after_raids', $this->afterRaids, array('rows' => 5, 'cols' => 100)) ?>
            	<br />
            	<br />
            	<hr />
            	<h2>Puinrapporten</h2>
            	<?= $this->formTextarea('debris_reports', $this->debrisReports, array('rows' => 5, 'cols' => 100)) ?>
			</div>
        </div>
    </div>
    </form>
    <div style="margin-left: 10px;">
<pre>
Kokx's CR Converter  Copyright (C) 2009  Kokx
This program comes with ABSOLUTELY NO WARRANTY; for details, <a href="COPYING.html#section15">click here</a>.
This is free software, and you are welcome to redistribute it
under certain conditions; <a href="COPYING.html#terms">click here</a> for details.
</pre>
    </div>
</div>

<? /* Google Analytics code */ ?>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
	var pageTracker = _gat._getTracker("<?= GOOGLE_GA_TRACKER_ID ?>");
	pageTracker._trackPageview();
} catch(err) {}</script>
</body>

</html>
