<?php
/**
 * This file is part of Kokx's CR Converter.
 *
 * Kokx's CR Converter is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Kokx's CR Converter is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Kokx's CR Converter.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category   KokxConverter
 * @license    http://www.gnu.org/licenses/gpl.txt
 * @copyright  Copyright (c) 2009 Kokx
 * @package    Kokx_Render
 */
?>
<html>

<head>
<title>Kokx's OGame CR converter</title>

<script type="text/javascript">
function toggleOptions()
{
	var options = document.getElementById('options');
	var link    = document.getElementById('hide');

	if (options.style.display == 'none') {
		options.style.display = 'block';
		link.innerHTML = 'Verberg Opties';
	} else {
		options.style.display = 'none';
		link.innerHTML = 'Toon Opties';
	}
}
</script>
<link rel="stylesheet" type="text/css" media="screen, handheld, projection" href="/css/main.css" />
</head>

<body>
<div id="container">
	<br />
	<div id="header">
		<h1>Kokx's OGame CR converter</h1>
	</div>
	<br />
	<div id="adsense">
		<script type="text/javascript"><!--
        google_ad_client = "<?= GOOGLE_AD_CLIENT ?>";
        google_ad_slot = "<?= GOOGLE_AD_SLOT ?>";
        google_ad_width = 728;
        google_ad_height = 90;
        //-->
        </script>
        <script type="text/javascript"
        src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
        </script>
	</div>
    <form method="post" action="">
    <div id="cr-container">
        <? if ($this->error): ?>
        	Incorrect gevechtsrapport
        <? endif; ?>
        <div id="cr-left">
            <?= $this->formTextarea('report', $this->report, array('rows' => 22, 'cols' => 60)) ?>
        </div>
        <div id="cr-right">
        	Titel: <?= $this->formText('title', $this->title, array('style' => 'width: 406px;')) ?><br />
            <?= $this->formTextarea('output', empty($this->rounds) ? '': $this->render('report/' . $this->theme . '.phtml'), array('cols' => 60, 'style' => 'height: 325px;')) ?>
        </div>
        <div id="cr-clear">&nbsp;</div>
    </div>
    <div id="submit-container">
        <?= $this->formSubmit('submit', 'Converteer!') ?>
    </div>
    <div id="options-container">
    	<div id="options-top">
    		<a href="javascript: void(0)" id="hide" onclick="toggleOptions()">Verberg Opties</a>
    	</div>
        <div id="options">
        	<h2>Algemene opties</h2>
        	<table border="0">
        		<tr>
        			<td><label for="theme">Skin</label></td>
        			<td><?= $this->formSelect('theme', $this->theme, null, array(
           				'kokx'         => 'kokx',
           				'kokx-nolines' => 'kokx-nolines',
           				'tsjerk'       => 'Albert Fish',
        			    'virus'        => 'ViRuS'
        			)) ?></td>
        			<td><label for="hidetime">Verberg de tijd</label></td>
        			<td><?= $this->formCheckbox('hidetime', null, array('checked' => $this->options['hideTime'])) ?></td>
        		</tr>
        		<tr>
        			<td><label for="middletext">Tekst in het midden van de CR</label></td>
        			<td><?= $this->formText('middletext', $this->options['middleText']) ?></td>
        			<td><label for="merge_fleets">Voeg vloten samen</label></td>
        			<td><?= $this->formCheckbox('merge_fleets', null, array('checked' => $this->options['mergeFleets'])) ?></td>
        		</tr>
        	</table>
            <div>
            	<br />
            	<hr />
            	<h2>Naraids</h2>
            	<?= $this->formTextarea('after_raids', $this->afterRaids, array('rows' => 5, 'cols' => 100)) ?>
            	<br />
            	<br />
            	<hr />
            	<h2>Puinrapporten</h2>
            	<?= $this->formTextarea('debris_reports', $this->debrisReports, array('rows' => 5, 'cols' => 100)) ?>
			</div>
        </div>
    </div>
    </form>
    <div style="margin-left: 10px;">
<pre>
Kokx's CR Converter  Copyright (C) 2009  Kokx
This program comes with ABSOLUTELY NO WARRANTY; for details, <a href="COPYING.html#section15">click here</a>.
This is free software, and you are welcome to redistribute it
under certain conditions; <a href="COPYING.html#terms">click here</a> for details.
</pre>
    </div>
</div>

<? /* Google Analytics code */ ?>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
	var pageTracker = _gat._getTracker("<?= GOOGLE_GA_TRACKER_ID ?>");
	pageTracker._trackPageview();
} catch(err) {}</script>
</body>

</html>
