<form method="post" action="">
<div id="cr-container">
    <? if ($this->error): ?>
        Incorrect gevechtsrapport
    <? endif; ?>
    <div id="cr-left">
        <?= $this->formTextarea('report', $this->data['report'], array('id' => 'cr-input')) ?>
    </div>
    <div id="cr-right">
        Titel: <?= $this->formText('title', 'TODO!!!', array('style' => 'width: 406px;')) ?><br />
        <?= $this->formTextarea('output', $this->rendered, array('id' => 'cr-output')) ?>
    </div>
    <div id="cr-clear">&nbsp;</div>
</div>
<div id="submit-container">
    <?= $this->formSubmit('submit', 'Converteer!') ?>
</div>
<div id="options-container">
    <div id="options-top">
        <a href="javascript: void(0)" id="hide" onclick="toggleOptions()">Verberg Opties</a>
    </div>
    <div id="options">
        <h2>Algemene opties</h2>
        <table border="0">
            <tr>
                <td><label for="theme">Skin</label></td>
                <td><?= $this->formSelect('theme', $this->settings['theme'], null, array(
                    'kokx'         => 'kokx',
                    'kokx-nolines' => 'kokx-nolines',
                    'tsjerk'       => 'Albert Fish',
                    'virus'        => 'ViRuS'
                )) ?></td>
                <td><label for="hidetime">Verberg de tijd</label></td>
                <td><?= $this->formCheckbox('hidetime', null, array('checked' => $this->settings['hide_time'])) ?></td>
            </tr>
            <tr>
                <td><label for="middletext">Tekst in het midden van de CR</label></td>
                <td><?= $this->formText('middletext', $this->settings['middle_text']) ?></td>
                <td><label for="merge_fleets">Voeg vloten samen</label></td>
                <td><?= $this->formCheckbox('merge_fleets', null, array('checked' => $this->settings['merge_fleets'])) ?></td>
            </tr>
        </table>
        <div>
            <br />
            <hr />
            <h2>Naraids</h2>
            <?= $this->formTextarea('raids', $this->data['raids'], array('rows' => 5, 'cols' => 100)) ?>
            <br />
            <br />
            <hr />
            <h2>Puinrapporten</h2>
            <?= $this->formTextarea('harvest_reports', $this->data['harvest_reports'], array('rows' => 5, 'cols' => 100)) ?>
        </div>
    </div>
</div>
</form>
