<? if (count($this->report->getHarvestReports()) > 0): ?>
	<? foreach ($this->report->getHarvestReports() as $hr): ?>
		_____________________________________

        <?= $this->translate("Your ") . $this->colorNumber($hr->getRecyclers(), '#FC850C') . $this->translate(" recycler(s) have a total cargo capacity of ") . $this->colorNumber($hr->getCapacity(), '#FC850C') ?>.
        <?= $this->translate("At the target, ") . $this->colorNumber($hr->getFieldMetal(), '#FC850C') . $this->translate(" metal and ") . $this->colorNumber($hr->getFieldCrystal(), '#FC850C') . $this->translate(" crystal are floating in space.") . "\n" ?>
        <?= $this->translate("You have harvested %s metal and %s crystal.", $this->colorNumber($hr->getMetal(), '#FC850C'), $this->colorNumber($hr->getCrystal(), '#FC850C')) ?>

		<? $percent = (($hr->getFieldMetal() + $hr->getFieldCrystal()) > 0) ? ($hr->getMetal() + $hr->getCrystal()) / ($hr->getFieldMetal() + $hr->getFieldCrystal()) * 100 : 0 ?>
		<?= $this->translate("Recycled: ") . $this->colorNumber($percent, '#FC850C') ?>%
    <? endforeach; ?>
    __________________________

	<?= $this->translate("A total of ") . $this->colorNumber($this->totalDebris, '#FC850C') . $this->translate(" units debris has been recycled.") ?>

<? endif; ?>
