<? if (count($this->report->getHarvestReports()) > 0): ?>
	<? foreach ($this->report->getHarvestReports() as $hr): ?>
		_____________________________________

		Je <?= $this->colorNumber($hr->getRecyclers(), '#FC850C') ?> recyclers hebben een totale opslagcapaciteit van <?= $this->colorNumber($hr->getCapacity(), '#FC850C') ?>.
		In het bestemmingsveld zweven <?= $this->colorNumber($hr->getFieldMetal(), '#FC850C') ?> metaal en <?= $this->colorNumber($hr->getFieldCrystal(), '#FC850C') ?> kristal in de ruimte.
		Je hebt <?= $this->colorNumber($hr->getMetal(), '#FC850C') ?> metaal en <?= $this->colorNumber($hr->getCrystal(), '#FC850C') ?> kristal opgehaald.

		<? $percent = ($hr->getMetal() + $hr->getCrystal()) / ($hr->getFieldMetal() + $hr->getFieldCrystal()) * 100 ?>
		Opgehaald: <?= $this->colorNumber($percent, '#FC850C') ?>%
    <? endforeach; ?>
    __________________________

	Er is een totaal van <?= $this->colorNumber($this->totalDebris, '#FC850C') ?> Eenheden puin opgehaald.
<? endif; ?>
