<? if ($this->totalRaids > 0): ?>
	De aanvaller heeft een totaal van <?= $this->colorNumber($this->totalRaids, '#FC850C') ?> Eenheden gestolen.
<? endif; ?>
	__________________

	[color=#3183E7][size=16][b]Totale samenvatting winst/verlies:[/b][/size][/color]
<? if ($this->report->getWinner() == Default_Model_CombatReport::ATTACKER): ?>
<?php
// calculate the result
$attackerResult = $this->totalDebris + $this->totalRaids - $this->report->getLossesAttacker();
$defenderResult = $this->report->getLossesDefender();
?>
	De aanvaller heeft <?= $this->colorNumber(abs($attackerResult), '#FC850C') ?> Eenheden <?= ($attackerResult > 0) ? 'winst' : 'verlies' ?> gemaakt.
	De verdediger heeft <?= $this->colorNumber($defenderResult, '#FC850C') ?> Eenheden verlies gemaakt.
<? elseif ($this->report->getWinner() == Default_Model_CombatReport::DRAW): ?>
<?php
// calculate the result
$attackerResult = $this->totalDebris + $this->totalRaids - $this->report->getLossesAttacker();
$defenderResult = $this->report->getLossesDefender();
?>
    De aanvaller heeft <?= $this->colorNumber(abs($attackerResult), '#FC850C') ?> Eenheden <?= ($attackerResult > 0) ? 'winst' : 'verlies' ?> gemaakt.
    De verdediger heeft <?= $this->colorNumber($defenderResult, '#FC850C') ?> Eenheden verlies gemaakt.
<? else: /* Defender is the winner */ ?>
<?php
// calculate the result
$attackerResult = $this->report->getLossesAttacker();
$defenderResult = $this->totalDebris - $this->report->getLossesDefender();
?>
	De aanvaller heeft <?= $this->colorNumber($attackerResult, '#FC850C') ?> Eenheden verlies gemaakt.
	De verdediger heeft <?= $this->colorNumber(abs($defenderResult), '#FC850C') ?> Eenheden <?= ($defenderResult > 0) ? 'winst' : 'verlies' ?> gemaakt.
<? endif; ?>

<? /* and a link to the Converter site*/ ?>
[size=10][url=<?= LINK ?>]Converted by Kokx's CR Converter <?= VERSION ?> (skin: kokx)[/url][/size][/align]
