<? if ($this->report->getWinner() == Default_Model_CombatReport::DRAW): ?>
	Het gevecht eindigt in een remise.
<? elseif ($this->report->getWinner() == Default_Model_CombatReport::ATTACKER): ?>
	De aanvaller heeft het gevecht gewonnen!
<? else: ?>
	De verdediger heeft het gevecht gewonnen!
<? endif; ?>
De aanvaller steelt:
<? if ($this->report->getWinner() == Default_Model_CombatReport::ATTACKER): ?>
	<?= $this->colorNumber($this->report->getMetal()) ?> Metaal, <?= $this->colorNumber($this->report->getCrystal()) ?> Kristal en <?= $this->colorNumber($this->report->getDeuterium()) ?> Deuterium
	<? foreach ($this->report->getRaids() as $raid): ?>
	    <?= $this->colorNumber($raid->getMetal()) ?> Metaal, <?= $this->colorNumber($raid->getCrystal()) ?> Kristal en <?= $this->colorNumber($raid->getDeuterium()) ?> Deuterium
	<? endforeach; ?>
<? else: ?>
	- Metaal, - Kristal en - Deuterium
<? endif; ?>

