<?php
function formatNumber($number, $color = false)
{
	$number = number_format($number, 0, ',', '.');

	if ($color) {
		return '[color=#3183E7][b]' . $number . '[/b][/color]';
	} else {
		return $number;
	}
}
?>
[quote][center]De volgende vloten kwamen elkaar tegen op <?php
echo $this->time['date'];
if ($this->options['hideTime']) {
    echo ' --:--:--';
} else {
    echo ' ' . $this->time['time'];
}
?> , toen het tot een gevecht kwam:

<? /* the first round, attackers */ ?>
<? foreach ($this->rounds[0]['attackers'] as $slot): ?>
    [color=red][b]Aanvaller[/b][/color] <?= $slot['player']['name'] ?> ([X:XXX:XX])
    Wapens: XXX% Schilden: XXX% Romp beplating: XXX%
    [color=red]________________________________________________[/color]

    <? foreach ($slot['fleet'] as $ship => $number): ?>
        [color=#FC850C]<?= $ship ?> <?= formatNumber($number) ?>[/color]
    <? endforeach; ?>
    [color=red]_________________________________________[/color]

<? endforeach; ?>

<? /* the first round */ ?>
<? foreach ($this->rounds[0]['defenders'] as $slot): ?>
    [color=green][b]Verdediger[/b][/color] <?= $slot['player']['name'] ?> ([X:XXX:XX])
    Wapens: XXX% Schilden: XXX% Romp beplating: XXX%
    [color=green]________________________________________________[/color]

    <? foreach ($slot['fleet'] as $ship => $number): ?>
        [color=#1C84BE]<?= $ship ?> <?= formatNumber($number) ?>[/color]
    <? endforeach; ?>
    [color=green]_________________________________________[/color]

<? endforeach; ?>

<?= $this->options['middleText'] ?>



<?php
// make some simple calculations

$last = count($this->rounds) - 1;

/* the last round, attackers */ ?>
<? foreach ($this->rounds[$last]['attackers'] as $key => $slot): ?>
    [color=red][b]Aanvaller[/b][/color] <?= $slot['player']['name'] ?> ([X:XXX:XX])
    [color=red]________________________________________________[/color]

    <?php
    // calculations for the first round
    if (isset($this->rounds[0]['attackers'][$key])) {
        $oldSlot = $this->rounds[0]['attackers'][$key];

        if ($slot['player']['name'] != $oldSlot['player']['name']) {
            unset($oldSlot);
        }
    }
    ?>
    <? if (empty($slot['fleet'])): ?>
    	[b]Vernietigd![/b]
    <? elseif(isset($oldSlot)): ?>
    	<? foreach ($oldSlot['fleet'] as $ship => $number): ?>
    		<? $slot['fleet'][$ship] = isset($slot['fleet'][$ship]) ? $slot['fleet'][$ship] : 0 ?>
            [color=#FC850C]<?= $ship ?> <?= formatNumber($slot['fleet'][$ship]) ?> [b](-<?= formatNumber($number - $slot['fleet'][$ship]) ?>)[/b][/color]
        <? endforeach; ?>
    <? else: ?>
        <? foreach ($slot['fleet'] as $ship => $number): ?>
            [color=#FC850C]<?= $ship ?> <?= formatNumber($number) ?>[/color]
        <? endforeach; ?>
    <? endif; ?>
    [color=red]_________________________________________[/color]
    <? unset($oldSlot) ?>

<? endforeach; ?>

<? /* the last round for the defenders */ ?>
<? foreach ($this->rounds[$last]['defenders'] as $key => $slot): ?>
    [color=green][b]Verdediger[/b][/color] <?= $slot['player']['name'] ?> ([X:XXX:XX])
    [color=green]________________________________________________[/color]

    <?php
    // calculations for the first round
    if (isset($this->rounds[0]['defenders'][$key])) {
        $oldSlot = $this->rounds[0]['defenders'][$key];

        if ($slot['player']['name'] != $oldSlot['player']['name']) {
            unset($oldSlot);
        }
    }
    ?>
    <? if (empty($slot['fleet'])): ?>
    	[b]Vernietigd![/b]
    <? elseif(isset($oldSlot)): ?>
    	<? foreach ($oldSlot['fleet'] as $ship => $number): ?>
    		<? $slot['fleet'][$ship] = isset($slot['fleet'][$ship]) ? $slot['fleet'][$ship] : 0 ?>
            [color=#1C84AE]<?= $ship ?> <?= formatNumber($slot['fleet'][$ship]) ?> [b](-<?= formatNumber($number - $slot['fleet'][$ship]) ?>)[/b][/color]
        <? endforeach; ?>
    <? else: ?>
        <? foreach ($slot['fleet'] as $ship => $number): ?>
            [color=#1C84AE]<?= $ship ?> <?= formatNumber($number) ?>[/color]
        <? endforeach; ?>
    <? endif; ?>
    [color=green]_________________________________________[/color]
    <? unset($oldSlot) ?>

<? endforeach; ?>

<? /* Make up the results */ ?>

<? if ($this->result['winner'] == Kokx_Parser_CrashReport::NONE): ?>
	Het gevecht eindigt in een remise.
<? elseif ($this->result['winner'] == Kokx_Parser_CrashReport::ATTACKER): ?>
	De aanvaller heeft het gevecht gewonnen!
<? else: ?>
	De verdediger heeft het gevecht gewonnen!
<? endif; ?>
De aanvaller steelt:
<? if ($this->result['winner'] == Kokx_Parser_CrashReport::ATTACKER): ?>
	<?= formatNumber($this->result['stolen']['metal'], true) ?> Metaal, <?= formatNumber($this->result['stolen']['crystal'], true) ?> Kristal, <?= formatNumber($this->result['stolen']['deut'], true) ?> Deuterium
	<? foreach ($this->raids as $raid): ?>
	    <?= formatNumber($raid['metal'], true) ?> Metaal, <?= formatNumber($raid['crystal'], true) ?> Kristal, <?= formatNumber($raid['deut'], true) ?> Deuterium
	<? endforeach; ?>
<? else: ?>
	- Metaal, - Kristal en - Deuterium
<? endif; ?>

De aanvaller heeft een totaal van <?= formatNumber($this->result['attackerlosses'], true) ?> Eenheden verloren.
De verdediger heeft een totaal van <?= formatNumber($this->result['defenderlosses'], true) ?> Eenheden verloren.
Op deze coördinaten in de ruimte zweven nu <?= formatNumber($this->result['debris']['metal'], true) ?> Metaal en <?= formatNumber($this->result['debris']['crystal'], true) ?> Kristal.
<? if ($this->result['moonchance'] > 0): ?>
	De kans dat een maan ontstaat uit het puin is <?= formatNumber($this->result['moonchance'], true) ?> %
<? endif; ?>
<? if (!empty($this->debris)): ?>

	<? foreach ($this->debris as $debris): ?>
		_____________________________________

		Je <?= formatNumber($debris['recs'], true) ?> recyclers hebben een totale opslagcapaciteit van <?= formatNumber($debris['storage'], true) ?>. In het bestemmingsveld zweven <?= formatNumber($debris['fieldmetal'], true) ?> metaal en <?= formatNumber($debris['fieldcrystal'], true) ?> kristal in de ruimte. Je hebt <?= formatNumber($debris['metal'], true) ?> metaal en <?= formatNumber($debris['crystal'], true) ?> kristal opgehaald.
    <? endforeach; ?>

<? endif; ?>

<? /* and a link to the A Team site*/ ?>
[size=10][url=http://converter.ateam-ogame.nl/]Converted by the A Team CR converter <?= VERSION ?>[/url][/size][/center][/quote]
