<?php
$rounds = $this->report->getRounds();
?>

<? /* attackers */ ?>
<? foreach ($rounds[0]->getAttackers() as $fleet): ?>
    [color=red][b]<?= $this->translate("Attacker") ?>[/b][/color] <?= $fleet->getPlayer() . "\n" ?>
    <? foreach ($fleet->getShips() as $ship): ?>
        <?= $this->formatShip(true, $ship); ?>
    <? endforeach; ?>

<? endforeach; ?>
<? /* defenders */ ?>
<? foreach ($rounds[0]->getDefenders() as $fleet): ?>
    [color=green][b]<?= $this->translate("Defender") ?>[/b][/color] <?= $fleet->getPlayer() . "\n" ?>
    <? foreach ($fleet->getShips() as $ship): ?>
        <?= $this->formatShip(false, $ship); ?>
    <? endforeach; ?>

<? endforeach; ?>

